
var lg={	downMsg : '<br/><br/><h1>帮助</h1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您可以通过“下载轨迹数据”功能，下载指定设备某一日期内的移动痕迹。<br/><br/>步骤：<br/>1.选择需要下载的指定设备。<br/> 2.输入需要下载的具体日期。<br/> 3.单击“下载KML轨迹文件”按钮。<br/><br/><span style="color:red;">注意：如果单击“下载”按钮， 出现“没有找到有效的轨迹数据!”提示信息，表示当前没有你需要<br/>下载的数据。 </span><br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;下载的轨迹文件的格式是Google KML格式，如:“文件名.kml”。安装 Google Earth后。双击KML<br/>文件，会通过Google Earth工具打开。<BR/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"KML轨迹文件"会将设备的移动痕迹以红线动态的描绘在Google地图上。<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br/><br/>附注:下载 Google Earth 请点击&nbsp;<a href="http://dl.google.com/earth/client/ge4/release_4_3/googleearth-win-plus-4.3.7284.3916.exe"><font color="blue">这里</font></a> <br/>',
	startPk : "开始回放",
	stop : "停止",
	bTime : [ "对不起！本系统暂不提供时间段跨度超过", "天以上的统计数据查询！请将查询时间段跨度改为不超过" ],
	playOverTip : [ "轨迹回放完毕!!时间从 ", "到" ],
	totalTime : "总时间",
	duration : "运行",
	kPerH : "公里/小时",
	// globe
	lang : "cn",
	googleKey : "http://ditu.google.cn/",
	lng : "经度",
	lat : "纬度",
	latlng : "经纬度",
	snew : "新货",
	skt : "开通",
	sbk : "退货",
	swx : "维修",
	stj : "停机",// 销售状态
	sdw : "定位状态",
	sdw0 : "未定位",
	sdw1 : "已定位",
	p : "&nbsp;位置:",
	p1 : "位置",// 定位状态
	srun0 : "未上线",
	srun1 : "离线",
	srun2 : "静止",
	srun3 : "行驶",
	srun4 : "快速行驶",
	srun5 : "超速行驶",
	srun6 : "全部",
	arrear : "欠费",// 运行状态
	date : "日期",
	time : "时间",
	y : "年",
	d : "天",
	h : "小时",
	m : "分",
	s : "秒",
	due : "到期时间",
	serviceYear : "服务年限",
	saleTime : "销售时间",
	factoryTime : "出厂日期",
	activeTime : "开通日期",
	dwtime : "定位时间",
	heartTime : "心跳时间",
	sendtime : "发送时间",
	utime : "信号时间",
	update0 : "关闭更新",
	update1 : "打开更新",
	view : "全景",
	target : "目标",
	mi : "米",
	km : "公里",

	on : "开启",
	off : "熄火",
	locked : '锁定&nbsp;<span style="color:black">[<span class="lock" style="color:#5C97E0">?</span>]</span>',
	unlock : '解锁',
	commandSuccess : '恭喜您，设备执行命令成功！\n响应：',
	serviceTimeOut : '服务器开小差了，请重试下吧~',
	createTime : '创建时间',
	zoneAlarm : '区域报警',
	msgtit0 : "提示",
	msgtit1 : "成功",
	msgtit2 : "失败",
	lockedMove : "锁定后此车随地图移动.",
	fence : '栅栏',
	electronic : '区域报警&nbsp;<span class="enclosure-item" style="color:black">[<span class="enclosure-item custom" style="color:#5C97E0">?</span>]</span>&nbsp;',
	rectangle : '矩形',
	round : '圆形',
	save : '保存',
	enclocureInfo : '启用当前区域报警',
	mapRange : '当前区域',
	effective : '生效时间',
	startTime : '开始',
	endTime : '结束',
	isOn : '是否开启',
	timeNoBlank : '开始时间和结束时间不能为空',
	dragInfo : '拖动调整栅栏范围.',
	byTime : '按日期',
	byRange : '按时段',
	custom : '自定义',
	defautMiles : '方圆200米',
	enable : '启用',
	out : '停用',// 弹出窗口提示信息标题

	// loading 信息
	sendSuc : "消息发送成功",
	sendFail : "消息发送失败",
	updateSuc : "数据更新成功....",
	updateFali : "数据更新失败....",
	subvali : "正在验证.....请等待...",
	loadfali : "数据加载失败...请重试",
	fload : "正在加载数据....",
	leadin : "正在提交数据.....请等待...",
	sendCmd : '正在发送指令.....请稍候...',
	cardCount : "卡数量",
	cardCountFormat : "卡数量的格式错误",
	generateFail : "充值卡生成失败,请重试",
	infuseSuccess : "设备充值成功",
	checkMsg : "请确认以上信息",
	groupName : '组',
	yes : '吗?',
	taxfeeFail : "设备续费失败",
	taxfeeSuc : "设备续费成功",
	overSpeed : "超速速度不得小于",
	beNumber : "必须是数字",
	moveSuc : "设备转移成功.",
	moveFail : "设备转移失败.",
	moveGropFail : "移动失败",
	addGroupFail : "添加组失败",
	reNameFail : "修改组名失败",
	delGroupFail : "删除组失败",
	delGroupSuccess : "删除组成功.",
	addGroupSuccess : "添加组成功.",
	delDefault : "默认组不可以删除！",
	moveCustomSuc : "客户转移成功",
	moveCustomFail : "客户转移失败",
	moveCustomTip : "不能将客户转移到自己或子帐号下",
	waiting : '下达命令成功，设备正在响应，勿关窗口哟！',
	// tips
	ctimetip : "查询的时间跨度不能大于 ",
	msgcon0 : "请选择",
	msgcon1 : "查询的设备,IMEI号必须至少是后5位以上的数字!",
	msgcon2 : "请输入要搜索的设备名",
	overSspeed : "超速速度必须为数字",
	timeOut : "操作超时",
	selectSubCustomer : "你名下没有子客户,不能发送消息",
	nodata : "没有查询到数据",
	distime : "开始时间不能大于结束时间",
	terror : "时间输入有误",
	addGroupTip : "请输入设备名/车牌号",
	needtax : "该设备已欠费",
	imeivali : "IMEI号必须是12或15个字符长度的数字组成",
	imeitip : 'IMEI号必须为12或15个字符长度的数字,导入多个IMEI号用","号分隔',
	saleImeiTip : "IMEI号必须是由5-20个字符长度的数字组成",
	rightMenuTip : "右键查看功能菜单",
	passvali : "两次输入的密码不一致,请重新输入",
	selUTip : "选择客户",
	fsuc : "以下设备导入成功",
	pexist : "以下设备已经存在",
	lfaluler : "IMEI号导入失败....",
	thoseTargets : "以下设备",
	companyNameTip : "客户名称必须不能为空",
	addUsuc : "客户添加成功...",
	logNameVali : "登陆名的第一个字符不能为数字",
	delSelfTip : "你无权删除你自己的账号",
	delUTip : "您确定要删除该客户吗？",
	selectTarget : "请选择设备...",
	selectCustom : "请选择客户",
	resetpwdtip : "你确定要重置密码吗？",
	resetpwdfail : "重置密码失败,请重试.....",
	userExist : "该登陆名已经存在!请选择其他用户名!",
	addFali : "数据添加失败",
	resetpwdsuc : "密码重置成功,您现在的密码是",
	saleCheck : "您确定要销售吗?",
	generateCheck : "您确定要生成当前充值卡吗?",
	SimNumTip : "SIM卡号必须为长度小于20位的数字",
	carNumExistTip : "您输入的车牌号码在系统中已存在，请重新输入",
	stattip : "请选择里程统计的日期",
	carNumFormatTip : "车牌号格式错误",
	dealedtip : "请不要重复处理",
	sucpwdtip : "密码已更新",
	falipwdtip : "密码更新失败!!",
	sendzltip : "发指令前请再次确认登陆账号",
	dealedsuc : "报警处理成功",
	maptip : "Google map暂不支持当前浏览器！",
	zoomMax : "已经到达最大缩放级别了",
	notblank : "不能为空",
	notspecial : "不能包含特殊字符",
	delCallTip : [ "ID为空", "删除成功", "当前客户名下存在设备数据", "存在下级客户", "当前客户名下存在充值卡记录" ],
	saleCallTip : [ "销售成功!", "没要找到您要销售的设备", "该设备已在所选客户名下,请勿重复销售!", "设备销售完成", "设备销售失败", "以下设备已在当前客户下", "以下IMEI号销售成功",
			"该设备已经在销售设备信息中,请不要重复添加!" ],
	internet : [ "网速非常好", "非常好", "很好", "中等", "较低", "非常低", "您的网速过慢，实时监控将受到影响！" ],
	stopMonitor : "实时监控停止",
	isGetting : "正在获取...",
	viewPosForbid : "不能查看位置",
	noImei : "没有找到你输入的IMEI号",
	infusePlatEnd : "充值后平台到期时间为:",
	infuseTip : [ "充值成功", "设备IMEI号不存在", "设备IMEI号不在当前登录客户名下", "无效充值号", "充值号已经被使用过", "充值过程中发生异常", "终身客户不需要再充值",
			"您已经在3天内充过值" ],
	superNameTip : "客户名称中不能包含单引号或双引号字符",
	warnTips : "系统报警信息提示",
	addGroupNameTip : "组名中不能包含单引号或双引号字符",
	parValue : "面值",
	generateTime : "生成时间",
	bundImei : "设备号(IMEI)",
	cardNumer : "充值卡号",
	notLocation : "该设备处于未定位状态",
	distanUP : "用户到期时间不得大于平台到期时间超过6个月以上",

	proaccount : "短号",
	newBie : "新手上路",
	tax : '缴费',
	product : "产品",
	client : "客户",
	type : "类型",
	sclient : "选中客户",
	pro : "设备",
	name : "名称",
	status : "状态",
	speed : "速度",
	account : "设备短号",
	pimei : "设备号(IMEI)",
	ptype : "型号",
	factoryDate : "出厂时间",
	createTime : "安装时间",
	userEnd : "用户到期",
	list : "列表",
	allp : "所有设备",
	hidn : "隐藏设备名",
	shown : "显示所有设备名",
	number : "号码",
	error : "错误",
	ownPhone : "车主电话",
	nums : "数量",

	// button
	promanage : "设备信息",
	add : "新增",
	manage : "管理",
	search : "搜索",
	select : "选择",
	resetPwd : "重置密码",
	updatepwd : "修改密码",
	leadin : "导入",
	delall : "删除所有",
	del : "删除",
	areaPlayBack : "区域回放",
	active : "销售开通",
	statLC : "里程统计",
	statCS : "超速统计",
	downgj : "下载轨迹",
	runct : "运行统计",
	pback : "回放",
	pback1 : "轨迹回放",
	track : "跟踪",
	searchw : "报警统计",
	zl : "设备指令",
	cutyd : "远程断油电",
	repyd : "远程恢复油电",
	checkp : "查询定位",
	checkr : "查询指令记录",
	simei : "按IMEI号搜",
	sname : "按设备名搜",
	addCustom : "新增客户",
	ok : "确定",
	sub : "提交",
	cancel : "取消",
	rset : "重置",
	rload : "重载",
	searchpro : "设备查询",
	searchIMEI : "搜 索",
	sale : "销售",
	enlarge : "放大",
	clos : "关闭",
	more : "更多<small>▼</small>",
	set : "设置",
	view : "查看",
	taxNotice : "缴费通知",
	send : "发送",
	viewDetail : "查看详细",
	detail : "详细",
	moveTo : "转移",
	backList : "返回列表",
	batchSale : "批量销售",
	batchMove : "批量转移",
	pMove : "设备转移",
	refresh : "刷 新",
	edit : "修改",
	generate : "生成充值号",
	infuse : "设备充值",
	inParValue : "充值",
	change : "更改",
	expand : "展开",
	collspan : "收起",
	// array
	hangxiang : [ "正北向", "北向", "东北向偏北", "东北向", "东北向偏东", "正东向", "东向", "东南向偏东", "东南向", "东南向偏南", "正南向", "南向", "西南向偏南",
			"西南向", "西南向偏西", "正西向", "西向", "西北向偏西", "西北向", "西北向偏北" ],
	wtype : [ "正常", "震动报警", "断电报警", "低电报警", "SOS求救", "超速报警", "离线报警", "栅栏报警", "超速报警", "超速报警" ],
	backMess : {
		flowID : '流水号',
		SEND_SUCCESS : "指令下发成功",
		SEND_FAIL : "指令下发失败",
		PWD_ERROR : "密码错误",
		NOT_CUSTOMER : "客户不存在",
		USER_LEAVE : "设备离线,不能发指令"
	},
	cmdType : {
		DWXX : '定位指令',
		DYD : '断油电指令',
		HFYD : '恢复油电指令'
	},
	w : [ '星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六' ],
	statusType : [ '网页发出指令', '网关收到指令', '网关判断不满足发送指令条件', '设备不在线', '网关发送指令', '终端响应指令' ],
	warnData : [ [ '所有报警', 'ALL' ], [ '震动报警', '1' ], [ '断电报警', '2' ], [ '低电报警', '3' ], [ 'SOS求救', '4' ],
			[ '超速报警', '5' ], [ '离线报警', '6' ], [ '栅栏报警', '7' ] ],
	warnDealWith : [ '未处理', '已处理', '不限' ],
	gradeDate : {
		c4 : '经销商',
		c5 : '汽修厂',
		c6 : '租赁',
		c7 : '物流',
		c8 : '用户'
	},
	msgRead : [ "未读", "已读消息", "已读" ],
	serviceEnd : [ "已过期", "天内过期", "天后过期", "今日到期" ],
	searchList : [ "查询到", "条记录,请选择:" ],
	moveCustom : [ "你确定要将客户", "转移到", "名下吗?" ],
	mgsType : {
		msg1 : "缴费通知",
		msg9 : "普通消息"
	},

	// words
	stip : "设备名/IMEI/车牌号",
	stip1 : "客户名/账号",
	logName : "登陆名",
	warn : "报警",
	cmd : "指令",
	response : "响应",
	mess : "信息",
	idle : "停留",
	sign : "信号",
	pos : "定位",
	exper : "体验",
	runDetail : "统计详单",
	start : " 开 始：",
	end : " 结 束：",
	sarea : "经过区域设备",
	atit : "区域设置",
	map : "地图",
	num : "序号",
	monitor : "监控",
	account : "账号",
	owner : "所属客户",
	platf : "服务年限",
	oney : "一年期",
	threey : "三年期",
	otherp : "外挂平台",
	remark : "备注信息",
	pwd : "密码",
	opwd : "旧密码",
	npwd : "新密码",
	rpwd : "确认密码",
	cfirm : "确认",
	course : "航向",
	operate : "操作",
	warntit : "报警信息报表",
	leadout : " 导出 ",
	stattime : "&nbsp;&nbsp;统计日期&nbsp;&nbsp;",
	tmovement : "总里程(单位:Km)",
	toverspeed : "总超速次数",
	mileagetit : "里程统计报表",
	dealed : "处理",
	movement : "里程",
	viewpos : "查看位置",
	timelywarntit : "报警信息",
	icon : "更换图标",
	format : "格式",
	phone : "电　话",
	contact : "联系人",
	address : "地　址",
	oSpeed : "超速",
	updateMsg : "更新信息",
	adduwait : "添加客户信息",
	addutit : "新增下级客户",
	cardNum : "卡号",
	carNum : "车牌号",
	pCompany : "所属客户",
	updateUTit : "客户信息",
	grate : "类型",
	companyName : "客户名称",
	SuperCustom : "上级客户",
	ServerProvider : "服务商",
	tagInfo : "设备信息",
	tagName : "设备名",
	cmdDetail : "指令详细信息",
	title : "标题",
	sender : "发送者",
	content : "内容",
	viewMsg : "查看消息",
	custDetail : "客户详细信息",
	group : "默认组",
	setTimeZone : "设置时区",
	timeZone : "时区",
	cMove : "客户转移",
	simCard : "设备电话(SIM卡号)",
	message : "消息",
	warnVoice : "开启报警声音",
	yl : "油量",
	infushTime : "充值时间",
	allLift : "终身",
	moveGroup : "移动至组",
	nocust : "没有查询到相关的客户信息,查设备点",
	noproduct : "没有查询到相关的设备信息,查客户点",
	here : "这里"
};